### ISSUE TITLE
[Local battery] Charging time left estimates wrong

### ISSUE THREAD

**Issue by mario-g98** [pacjo/SmartspacerPlugins#13]
The charging time estimates of the Battery Info Target aren't correct. As a reference, the At a Glance widget of Lawnchair is showing proper estimates.

Local Battery Plugin
![Screenshot_20240726-173942_1](https://github.com/user-attachments/assets/8cb750f9-7cb8-44ed-a473-b27dc3023707)

Lawnchair's At a Glance
![Screenshot_20240726-174106_1](https://github.com/user-attachments/assets/bb3818dd-a635-4d7c-b4e1-912701de60a9)

![Screenshot_20240726-173944_1](https://github.com/user-attachments/assets/0cef0f5c-2cfe-412b-8683-8769e02225ad)

**Comment by pacjo** [comment]
I don't know. I'm using basically the same code as lawnchair ([see here](https://github.com/LawnchairLauncher/lawnchair/blob/fb92d554fde7aeaacd55cd7f993dd95363ac3a66/lawnchair/src/app/lawnchair/smartspace/provider/BatteryStatusProvider.kt#L50) and [here](https://github.com/pacjo/SmartspacerPlugins/blob/88e99c64b87196b4abeaf30313fdca4e77f51aa5/app/src/localbattery/src/java/providers/BatteryBroadcastProvider.kt#L41)).

The issue probably lies in refreshing. Mine does it whenever `ACTION_BATTERY_CHANGED` intent is received, while lawnchair gets it every time it's needed.

Due to battery drain concerns I won't be changing the way it works (at least by default). From my experience it's *good enough*.

but with that said, if someone would like to make it a option and make a PR, I'll be happy to merge it. Making it opt-in (just like flashlight prompt option in Smartspacer) seems like the way to go.

**Comment by mario-g98** [comment]
I don't know what device you are using, but on Pixel 7 the plugin is practically unusable. In a matter of seconds the time jumped through the following sequence: 10 min - 1 min - 20 min - 46 min - 13 min, while the system reported time was around 50 min.
