### ISSUE TITLE
[Local Battery] Charging estimate shows battery to be "full in less than a minute" when Adaptive Charging is enabled

### ISSUE THREAD

**Issue by FibreTTP** [pacjo/SmartspacerPlugins#8]
On my Pixel 7 Pro, when Adaptive Charging is turned on and active, the charging target's charging estimate will show the time to charge to be "less than a minute", when it is actually purposefully *scheduled* to complete in a larger amount of time.

![Screenshot_20240404-031601](https://github.com/pacjo/SmartspacerPlugins/assets/120446961/beafffe5-35bf-49d1-9bc9-b2550ca06e25)
![Screenshot_20240404-031647](https://github.com/pacjo/SmartspacerPlugins/assets/120446961/bc35c305-aa4d-453c-a665-25a592b309f5)

**Comment by pacjo** [comment]
I don't think I'm able to detect that. There are some mentions of adaptive charging in AOSP ([link](https://cs.android.com/search?q=isAdaptiveChargingSupported), but I don't know how to use them. (also they're on an older branch and not present in `main`)

On my rom (crDroid 10) I have something called *Charging control*, which looks promising, but I haven't tested that. Normally I just limit charging current to 750 mA with ACC and that seems to do the trick.

For now I'd suggest just disabling the estimate in settings. If a promising solution pops up (preferably in AOSP, since I don't want to maintain multiple vendor-specific workarounds), feel free to reopen.

**Comment by FibreTTP** [comment]
Yet another Pixel-specific, non-AOSP feature... thanks anyway, lol

I should probably note that it only does this when Adaptive Charging is actually engaged (typically overnight), so if I charge in the middle of the day, then it works fine :)
